<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by lupdate-zig. To update this file, run the 'lupdate-zig' command below. -->
<!-- lupdate-zig -i "../main.zig" -o "mdoutliner_en.ts" -l "en_US" -->
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>Main</name>
    <message>
        <location filename="main.zig" line="71"/>
        <source>&amp;File</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="75"/>
        <source>&amp;New Tab</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="79"/>
        <source>Ctrl+N</source>
        <comment>New tab</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="87"/>
        <source>&amp;Open...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="91"/>
        <source>Ctrl+O</source>
        <comment>Open a file</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="99"/>
        <source>&amp;Exit</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="103"/>
        <source>Ctrl+Q</source>
        <comment>Quit</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="111"/>
        <source>&amp;Options</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="115"/>
        <source>&amp;Language</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="119"/>
        <source>&amp;English</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="123"/>
        <source>&amp;French</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="127"/>
        <source>&amp;Spanish</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="131"/>
        <source>&amp;Help</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.zig" line="135"/>
        <source>&amp;About Qt</source>
        <translation></translation>
    </message>
</context>
</TS>
